#docker run -p 8080:8080 -p 50000:50000 -v /var/jenkins_home:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock -d --name #jenkins jenkins/jenkins:lts

services:
    jenkins:
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - '/var/jenkins_home:/var/jenkins_home'
            - '/var/run/docker.sock:/var/run/docker.sock'
        container_name: jenkins
        image: 'jenkins/jenkins:lts'


# docker-compose up --detach

#NOTE:------------
##Set Permission If failed to get access       
## sudo chown -R 1000:1000 /var/jenkins_home